-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."mariokart8deluxe_battle_match_players" add column "point" integer
--  null;
