-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."lethalcompany_ship_days" add column "start_time" timestamptz
--  null;
