-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."program_live_archives" add column "youtube_video_id" uuid
--  null;
