-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."youtube_videos" add column "scheduled_start_time" timestamptz
--  null;
