-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."crawler__youtube_channel_video_configs" add column "found_at" timestamptz
--  not null;
