table:
  name: crawler__youtube_channel_video_configs
  schema: public
object_relationships:
  - name: youtube_channel
    using:
      foreign_key_constraint_on: remote_youtube_channel_id
  - name: youtube_video
    using:
      foreign_key_constraint_on: remote_youtube_video_id
insert_permissions:
  - role: crawler
    permission:
      check: {}
      columns:
        - auto_updated_at
        - remote_youtube_channel_id
        - remote_youtube_video_id
    comment: ""
select_permissions:
  - role: crawler
    permission:
      columns:
        - auto_update_enabled
        - auto_updated_at
        - comment
        - created_at
        - id
        - remote_youtube_channel_id
        - remote_youtube_video_id
        - updated_at
      filter: {}
      allow_aggregations: true
    comment: ""
update_permissions:
  - role: crawler
    permission:
      columns:
        - auto_updated_at
      filter: {}
      check: {}
    comment: ""
