-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."youtube_channels" add column "auto_updated_at" timestamptz
--  null;
