-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."mariokart8deluxe_races" add column "mariokart8deluxe_race_rule_id" uuid
--  null;
