-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."fallguys_custom_round_twitter_announcements" add column "is_agent_tweet" boolean
--  null;
