-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."program_twitter_announcements" add column "person_id" uuid
--  null;
