-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."mariokart8deluxe_courses" add column "in_cup_index" integer
--  null;
