-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."lethalcompany_weathers" add column "is_labeled" boolean
--  not null;
